<16>// Module included in the following assemblies:
//
// * machine_management/creating-infrastructure-machinesets.adoc
// * machine_management/creating_machinesets/creating-machineset-rhv.adoc

[id="machineset-yaml-rhv_{context}"]
=  Sample YAML for a MachineSet Custom Resource on {rh-virtualization}

This sample YAML defines a machine set that runs on
{rh-virtualization} and creates nodes that are labeled with
`node-role.kubernetes.io/<node_role>: ""`

In this sample, `<infrastructure_id>` is the infrastructure ID label that is based on the cluster ID that you set when you provisioned the cluster, and `<role>` is the node label to add.

[source,yaml,subs="+quotes"]
----
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id> <1>
        machine.openshift.io/cluster-api-machine-role: <role> <2>
        machine.openshift.io/cluster-api-machine-type: <role> <2>
      name: <infrastructure_id>-<role> <3>
      namespace: openshift-machine-api
    spec:
      replicas: <number_of_replicas> <4>
      Selector: <5>
        matchLabels:
          machine.openshift.io/cluster-api-cluster: <infrastructure_id> <1>
          machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<role> <3>
      template:
        metadata:
          labels:
            machine.openshift.io/cluster-api-cluster: <infrastructure_id> <1>
            machine.openshift.io/cluster-api-machine-role: <role> <2>
            machine.openshift.io/cluster-api-machine-type: <role> <2>
            machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<role> <3>
        spec:
          metadata:
            labels:
              node-role.kubernetes.io/<role>: "" <2>
          providerSpec:
            value:
              apiVersion: ovirtproviderconfig.machine.openshift.io/v1beta1
              cluster_id: <ovirt-cluster-id> <6>
              template_name: <ovirt-template-name> <7>
              instance_type_id: <instance-type-id> <8>
              cpu: <9>
                cores: <number-of-cores> <10>
                sockets: <number-of-sockets> <11>
                threads: <number-of-threads> <12>
              memory_mb: <memory-size> <13>
              os_disk: <14>
                size_gb: <disk-size> <15>
              network_interfaces: <16>
                vnic_profile_id:  <vnic_profile_id> <17>
              credentialsSecret:
                name: ovirt-credentials <18>
              kind: OvirtMachineProviderSpec
              type: <workload-type> <19>
              userDataSecret:
                name: worker-user-data
----
<1> Specify the infrastructure ID that is based on the cluster ID that you set when you provisioned the cluster. If you have the OpenShift CLI (oc) installed, you can obtain the infrastructure ID by running the following command:
+
[source,terminal]
----
$ oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
----

<2> Specify the node label to add.

<3> Specify the infrastructure ID and node label.

<4> Specify the number of machines to create.

<5> Selector for the machines.

<6> Specify a UUID for the oVirt cluster to which this VM instance belongs.

<7> Specify the oVirt VM template to use to create the machine.

<8> (Optional) Specify the VM instance type. If you include this parameter, you do not need to specify the hardware parameters of the VM including CPU and memory because this parameter overrides all hardware parameters.

<9> (Optional) The CPU field contains configuration for the VM cpu, made of (Sockets * Cores * Threads).

<10> (Optional) Specify the number of sockets for a VM.

<11> (Optional) Specify the number of cores per socket.

<12> (Optional) Specify the number of threads per core.

<13> (Optional) Specify the size of a VM's memory in MiBs.

<14> (Optional) Root disk of the node.

<15> (Optional) Specify the size of the bootable disk in GiB.

<16> (Optional) List of the network interfaces of the VM. If you include this parameter, OCP discards all network interfaces from the template and creates new ones.

<17> (Optional) Specify the vNic profile ID.

<18> Specify the name of secret that holds the oVirt credentials.
<19> (Optional) Specify the workload type for which the instance is optimized. This value affects the `RHV VM` parameter. Supported values: `*desktop*`, `*server*`, `*high_performance*`

[NOTE]
====
Because {rh-virtualization} uses a template when creating a VM, if you don't specify a value for an optional parameter, {rh-virtualization} use the value for that parameter that is specified in the template.
====
